# Generated by Django 3.2.12 on 2022-03-18 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_number', models.CharField(max_length=30)),
                ('acct_type', models.CharField(choices=[('SAVING', 'SAVING'), ('FD', 'FD'), ('PPF', 'PPF')], max_length=10)),
                ('acct_name', models.CharField(max_length=30)),
                ('initial_balance', models.FloatField()),
                ('balance', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
