# Generated by Django 3.2.12 on 2022-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.FloatField(default=0),
        ),
    ]
