# Generated by Django 3.2.12 on 2022-03-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_auto_20220318_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='user',
            new_name='owner',
        ),
    ]
