# Generated by Django 3.2.12 on 2022-03-19 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_auto_20220319_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactions',
            name='txn_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
