# Generated by Django 3.2.12 on 2022-03-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_banktransactions_txn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactions',
            name='txn_date',
            field=models.DateField(),
        ),
    ]
