# Generated by Django 3.2.6 on 2021-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('share_price', models.FloatField()),
                ('txn_date', models.DateField()),
            ],
        ),
    ]
