# Generated by Django 3.2.6 on 2021-08-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20210817_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='logo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='txn_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('DIV', 'DIV')], max_length=4),
        ),
    ]
