# Generated by Django 3.2.6 on 2021-08-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_sharelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharelist',
            old_name='symbol',
            new_name='text',
        ),
    ]
